/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServersCreateIndexRouteImport } from './routes/servers/create/index'
import { Route as ServersCreateStoredRouteImport } from './routes/servers/create/stored'
import { Route as ServersCreateAwsSecretRouteImport } from './routes/servers/create/aws-secret'
import { Route as ServersServerIdEncryptedRouteImport } from './routes/servers/$serverId/encrypted'
import { Route as ServersServerIdLoadedRouteRouteImport } from './routes/servers/$serverId/_loaded/route'
import { Route as ServersServerIdLoadedIndexRouteImport } from './routes/servers/$serverId/_loaded/index'
import { Route as ServersServerIdLoadedInitializeRouteImport } from './routes/servers/$serverId/_loaded/initialize'
import { Route as ServersServerIdLoadedTenantCreateRouteImport } from './routes/servers/$serverId/_loaded/tenant/create'
import { Route as ServersServerIdLoadedTenantEnvIdRouteImport } from './routes/servers/$serverId/_loaded/tenant/$env/$id'

const ServersServerIdRouteImport = createFileRoute('/servers/$serverId')()

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServersServerIdRoute = ServersServerIdRouteImport.update({
  id: '/servers/$serverId',
  path: '/servers/$serverId',
  getParentRoute: () => rootRouteImport,
} as any)
const ServersCreateIndexRoute = ServersCreateIndexRouteImport.update({
  id: '/servers/create/',
  path: '/servers/create/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServersCreateStoredRoute = ServersCreateStoredRouteImport.update({
  id: '/servers/create/stored',
  path: '/servers/create/stored',
  getParentRoute: () => rootRouteImport,
} as any)
const ServersCreateAwsSecretRoute = ServersCreateAwsSecretRouteImport.update({
  id: '/servers/create/aws-secret',
  path: '/servers/create/aws-secret',
  getParentRoute: () => rootRouteImport,
} as any)
const ServersServerIdEncryptedRoute =
  ServersServerIdEncryptedRouteImport.update({
    id: '/encrypted',
    path: '/encrypted',
    getParentRoute: () => ServersServerIdRoute,
  } as any)
const ServersServerIdLoadedRouteRoute =
  ServersServerIdLoadedRouteRouteImport.update({
    id: '/_loaded',
    getParentRoute: () => ServersServerIdRoute,
  } as any)
const ServersServerIdLoadedIndexRoute =
  ServersServerIdLoadedIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ServersServerIdLoadedRouteRoute,
  } as any)
const ServersServerIdLoadedInitializeRoute =
  ServersServerIdLoadedInitializeRouteImport.update({
    id: '/initialize',
    path: '/initialize',
    getParentRoute: () => ServersServerIdLoadedRouteRoute,
  } as any)
const ServersServerIdLoadedTenantCreateRoute =
  ServersServerIdLoadedTenantCreateRouteImport.update({
    id: '/tenant/create',
    path: '/tenant/create',
    getParentRoute: () => ServersServerIdLoadedRouteRoute,
  } as any)
const ServersServerIdLoadedTenantEnvIdRoute =
  ServersServerIdLoadedTenantEnvIdRouteImport.update({
    id: '/tenant/$env/$id',
    path: '/tenant/$env/$id',
    getParentRoute: () => ServersServerIdLoadedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/servers/$serverId': typeof ServersServerIdLoadedRouteRouteWithChildren
  '/servers/$serverId/encrypted': typeof ServersServerIdEncryptedRoute
  '/servers/create/aws-secret': typeof ServersCreateAwsSecretRoute
  '/servers/create/stored': typeof ServersCreateStoredRoute
  '/servers/create': typeof ServersCreateIndexRoute
  '/servers/$serverId/initialize': typeof ServersServerIdLoadedInitializeRoute
  '/servers/$serverId/': typeof ServersServerIdLoadedIndexRoute
  '/servers/$serverId/tenant/create': typeof ServersServerIdLoadedTenantCreateRoute
  '/servers/$serverId/tenant/$env/$id': typeof ServersServerIdLoadedTenantEnvIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/servers/$serverId': typeof ServersServerIdLoadedIndexRoute
  '/servers/$serverId/encrypted': typeof ServersServerIdEncryptedRoute
  '/servers/create/aws-secret': typeof ServersCreateAwsSecretRoute
  '/servers/create/stored': typeof ServersCreateStoredRoute
  '/servers/create': typeof ServersCreateIndexRoute
  '/servers/$serverId/initialize': typeof ServersServerIdLoadedInitializeRoute
  '/servers/$serverId/tenant/create': typeof ServersServerIdLoadedTenantCreateRoute
  '/servers/$serverId/tenant/$env/$id': typeof ServersServerIdLoadedTenantEnvIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/servers/$serverId': typeof ServersServerIdRouteWithChildren
  '/servers/$serverId/_loaded': typeof ServersServerIdLoadedRouteRouteWithChildren
  '/servers/$serverId/encrypted': typeof ServersServerIdEncryptedRoute
  '/servers/create/aws-secret': typeof ServersCreateAwsSecretRoute
  '/servers/create/stored': typeof ServersCreateStoredRoute
  '/servers/create/': typeof ServersCreateIndexRoute
  '/servers/$serverId/_loaded/initialize': typeof ServersServerIdLoadedInitializeRoute
  '/servers/$serverId/_loaded/': typeof ServersServerIdLoadedIndexRoute
  '/servers/$serverId/_loaded/tenant/create': typeof ServersServerIdLoadedTenantCreateRoute
  '/servers/$serverId/_loaded/tenant/$env/$id': typeof ServersServerIdLoadedTenantEnvIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/servers/$serverId'
    | '/servers/$serverId/encrypted'
    | '/servers/create/aws-secret'
    | '/servers/create/stored'
    | '/servers/create'
    | '/servers/$serverId/initialize'
    | '/servers/$serverId/'
    | '/servers/$serverId/tenant/create'
    | '/servers/$serverId/tenant/$env/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/servers/$serverId'
    | '/servers/$serverId/encrypted'
    | '/servers/create/aws-secret'
    | '/servers/create/stored'
    | '/servers/create'
    | '/servers/$serverId/initialize'
    | '/servers/$serverId/tenant/create'
    | '/servers/$serverId/tenant/$env/$id'
  id:
    | '__root__'
    | '/'
    | '/servers/$serverId'
    | '/servers/$serverId/_loaded'
    | '/servers/$serverId/encrypted'
    | '/servers/create/aws-secret'
    | '/servers/create/stored'
    | '/servers/create/'
    | '/servers/$serverId/_loaded/initialize'
    | '/servers/$serverId/_loaded/'
    | '/servers/$serverId/_loaded/tenant/create'
    | '/servers/$serverId/_loaded/tenant/$env/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ServersServerIdRoute: typeof ServersServerIdRouteWithChildren
  ServersCreateAwsSecretRoute: typeof ServersCreateAwsSecretRoute
  ServersCreateStoredRoute: typeof ServersCreateStoredRoute
  ServersCreateIndexRoute: typeof ServersCreateIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servers/$serverId': {
      id: '/servers/$serverId'
      path: '/servers/$serverId'
      fullPath: '/servers/$serverId'
      preLoaderRoute: typeof ServersServerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servers/create/': {
      id: '/servers/create/'
      path: '/servers/create'
      fullPath: '/servers/create'
      preLoaderRoute: typeof ServersCreateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servers/create/stored': {
      id: '/servers/create/stored'
      path: '/servers/create/stored'
      fullPath: '/servers/create/stored'
      preLoaderRoute: typeof ServersCreateStoredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servers/create/aws-secret': {
      id: '/servers/create/aws-secret'
      path: '/servers/create/aws-secret'
      fullPath: '/servers/create/aws-secret'
      preLoaderRoute: typeof ServersCreateAwsSecretRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servers/$serverId/encrypted': {
      id: '/servers/$serverId/encrypted'
      path: '/encrypted'
      fullPath: '/servers/$serverId/encrypted'
      preLoaderRoute: typeof ServersServerIdEncryptedRouteImport
      parentRoute: typeof ServersServerIdRoute
    }
    '/servers/$serverId/_loaded': {
      id: '/servers/$serverId/_loaded'
      path: '/servers/$serverId'
      fullPath: '/servers/$serverId'
      preLoaderRoute: typeof ServersServerIdLoadedRouteRouteImport
      parentRoute: typeof ServersServerIdRoute
    }
    '/servers/$serverId/_loaded/': {
      id: '/servers/$serverId/_loaded/'
      path: '/'
      fullPath: '/servers/$serverId/'
      preLoaderRoute: typeof ServersServerIdLoadedIndexRouteImport
      parentRoute: typeof ServersServerIdLoadedRouteRoute
    }
    '/servers/$serverId/_loaded/initialize': {
      id: '/servers/$serverId/_loaded/initialize'
      path: '/initialize'
      fullPath: '/servers/$serverId/initialize'
      preLoaderRoute: typeof ServersServerIdLoadedInitializeRouteImport
      parentRoute: typeof ServersServerIdLoadedRouteRoute
    }
    '/servers/$serverId/_loaded/tenant/create': {
      id: '/servers/$serverId/_loaded/tenant/create'
      path: '/tenant/create'
      fullPath: '/servers/$serverId/tenant/create'
      preLoaderRoute: typeof ServersServerIdLoadedTenantCreateRouteImport
      parentRoute: typeof ServersServerIdLoadedRouteRoute
    }
    '/servers/$serverId/_loaded/tenant/$env/$id': {
      id: '/servers/$serverId/_loaded/tenant/$env/$id'
      path: '/tenant/$env/$id'
      fullPath: '/servers/$serverId/tenant/$env/$id'
      preLoaderRoute: typeof ServersServerIdLoadedTenantEnvIdRouteImport
      parentRoute: typeof ServersServerIdLoadedRouteRoute
    }
  }
}

interface ServersServerIdLoadedRouteRouteChildren {
  ServersServerIdLoadedInitializeRoute: typeof ServersServerIdLoadedInitializeRoute
  ServersServerIdLoadedIndexRoute: typeof ServersServerIdLoadedIndexRoute
  ServersServerIdLoadedTenantCreateRoute: typeof ServersServerIdLoadedTenantCreateRoute
  ServersServerIdLoadedTenantEnvIdRoute: typeof ServersServerIdLoadedTenantEnvIdRoute
}

const ServersServerIdLoadedRouteRouteChildren: ServersServerIdLoadedRouteRouteChildren =
  {
    ServersServerIdLoadedInitializeRoute: ServersServerIdLoadedInitializeRoute,
    ServersServerIdLoadedIndexRoute: ServersServerIdLoadedIndexRoute,
    ServersServerIdLoadedTenantCreateRoute:
      ServersServerIdLoadedTenantCreateRoute,
    ServersServerIdLoadedTenantEnvIdRoute:
      ServersServerIdLoadedTenantEnvIdRoute,
  }

const ServersServerIdLoadedRouteRouteWithChildren =
  ServersServerIdLoadedRouteRoute._addFileChildren(
    ServersServerIdLoadedRouteRouteChildren,
  )

interface ServersServerIdRouteChildren {
  ServersServerIdLoadedRouteRoute: typeof ServersServerIdLoadedRouteRouteWithChildren
  ServersServerIdEncryptedRoute: typeof ServersServerIdEncryptedRoute
}

const ServersServerIdRouteChildren: ServersServerIdRouteChildren = {
  ServersServerIdLoadedRouteRoute: ServersServerIdLoadedRouteRouteWithChildren,
  ServersServerIdEncryptedRoute: ServersServerIdEncryptedRoute,
}

const ServersServerIdRouteWithChildren = ServersServerIdRoute._addFileChildren(
  ServersServerIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ServersServerIdRoute: ServersServerIdRouteWithChildren,
  ServersCreateAwsSecretRoute: ServersCreateAwsSecretRoute,
  ServersCreateStoredRoute: ServersCreateStoredRoute,
  ServersCreateIndexRoute: ServersCreateIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
